### ISSUE TITLE
Need better field support.

### ISSUE THREAD

**Issue by jaffee** [pilosa/go-pilosa#103]
Field support feels a bit weird right now. if you have  a `*Frame`, you can call Field(name) to get a field as you would expect, but there is no way to set any options on that field, and an error is returned as a member of the field struct rather than a second return value.

Based on the way everything else works, I'd expect to do something like 

```go
schema, err := client.Schema()
index, err := schema.Index(name)
frame, err := index.Frame(name)
field, err := frame.IntField(name, min, max)
err = client.SyncSchema(schema)
client.Query(field.Range(...))
```

Though, I think we could actually do away with the errors on everything but Schema and SyncSchema and do all the validation in those methods. 

Currently, there is no easy way to "GetOrCreate" a field which is what is prompting this issue.

**Comment by yuce** [comment]
Closing this issue, since field stuff has changed quite a bit.
