### ISSUE TITLE
Unable to read back bits set in pilosa

### ISSUE THREAD

**Issue by maartenheremans** [pilosa/go-pilosa#120]
I 'm running a pilosa docker container: https://hub.docker.com/u/pilosa/ on my OSX host.

When running the code on the your github page from the quick overview I do not retrieve any results back. 
However, I can see in the web-ui of pilosa that the bit 42 is set on row 5 of myindex, myframe.
The code itself is not capable of reading the bit back out. It does not return an error but rather empty result arrays:

```
go run cmd/test2/main.go
Got bits:  []
[]
[]
```

I have the same behaviour in the real application i'm developing. I can set bits, retrieve them from the webui, but simple Bitmap queries from code do not work.

**Comment by yuce** [comment]
@maartenheremans Were you using the Go client from the master branch? There's a pretty big change coming to the Pilosa server, and master of Go client was modified to work with that. We've just merged a change to master that makes the Go client work with both the current Pilosa and the new. Can you give it a try with the latest Go client on master?

**Comment by jaffee** [comment]
@maartenheremans Thank you for the report.

It appears that gopilosa master is not compatible with v0.8.8 of Pilosa (which you get with the docker image). This unfortunately happens occasionally as we evolve APIs in our pre-1.0 state.

You have two options to work around this: 
1. Use the master branch of Pilosa (building from source is fairly straightforward), and running the built binary is as easy as `pilosa server`.
2. checkout version 0.8.0 of go-pilosa and use that. `git checkout v0.8.0`. Depending on what you're using for dependency management, you may wish to pin go-pilosa to this revision in Gopkg.toml or similar.

If you're just experimenting with Pilosa and want to track the latest and greatest features, I recommend route 1. If you need to depend on Pilosa in production, I recommend the second route, and you can wait to upgrade until we have tagged 0.9 releases of both Pilosa and the clients.

**Comment by jaffee** [comment]
Ah I didn't see @yuce's message before I posted. You're welcome to try pulling the latest go-pilosa and using that, but I would actually recommend you follow one of the two paths I outlined as go-pilosa:master and pilosa:v0.8 (or whatever the last release is) are not guaranteed to stay compatible in general.

**Comment by maartenheremans** [comment]
Thanks for the quick reply.

Since we are building production code I assume path 2 is the best. Our build pipeline however relies on 'go get'. Is there a versioned package available via gopkg.in ?

**Comment by jaffee** [comment]
We'd recommend using `dep`, but assuming that's not possible we can look into supporting `gopkg.in`.

**Comment by maartenheremans** [comment]
@yuce 
It now gives a proper error indicating a version mismatch.
I believe this is a good solution.

```
2018/02/27 21:21:40 Pilosa server's version is 0.8.8, does not meet the minimum required for this version of the client: >=0.9.0.
```

**Comment by yuce** [comment]
@maartenheremans We probably need to change/remove that message. It just tells that the client is now working in "legacy" mode (Pilosa <= 0.9). But everything should still work. You shouldn't be getting empty results now.

**Comment by yuce** [comment]
@maartenheremans Does using the master branch of the client solve the empty results problem? Can we close this issue?

**Comment by maartenheremans** [comment]
@yuce 
No it does not solve the problem.

The following is with the 0.8.8 pilosa version:
```
2018/02/28 21:12:08 Pilosa server's version is 0.8.8, does not meet the minimum required for this version of the client: >=0.9.0.
Got bits:  []
[]
[]
```

However, with the latest build of pilosa (build manually, ignore the 0.0.0 version):
```
2018/02/28 21:14:02 Pilosa server's version is 0.0.0, does not meet the minimum required for this version of the client: >=0.9.0.
Got bits:  [42]
[42]
[]
```

**Comment by jaffee** [comment]
That log is just a warning, it doesn't affect your results which I believe are correct. @yuce we should probably remove that log now that both versions are supported, right?

**Comment by yuce** [comment]
@maartenheremans The protobuf definitions in Pilosa server changed after v0.8.8 was released so current versions of Pilosa clients are not compatible with that version. We test our clients against both Pilosa master and Pilosa cluster-resize branch (which is going to become v0.9) and missed testing against v0.8.8 which as I mentoned has different protobuf definitions. The web UI uses JSON, so that change doesn't affect it.

As you mentioned, Go client on master is compatible with Pilosa on master. So you can use those together; or use Go client v0.8.0 and Pilosa v0.8.8 together. In that case a small change is required in your code: you will need to change `result.Bitmap()` to `result.Bitmap`. Please refer to the README of the Go client on v0.8.0 tag.

Thank you for bringing this issue to our attention and I am sorry for this error. I will remove Pilosa v0.8 compatibility badge and restore the original "incompatibility" message for the Go client.

**Comment by maartenheremans** [comment]
@yuce Thanks again for picking this up so quickly. I can indeed continue for now with both a latest build of pilosa and the go-client.
