### ISSUE TITLE
Add OptFrameCacheType option function

### ISSUE THREAD

**Issue by yuce** [pilosa/go-pilosa#146]

**Comment by travisturner** [comment]
@yuce if you see the TODO in PR https://github.com/pilosa/pilosa/pull/1351 on this [line](https://github.com/pilosa/pilosa/pull/1351/files#diff-38a0fa12b0c511105c3a411f0df3e318R75) I've noted that we should probably support all frame options in https://github.com/pilosa/pilosa/issues/1345:
```
type FrameOptions struct {
    Type        string      `json:"type,omitempty"`
    CacheType   string      `json:"cacheType,omitempty"`
    CacheSize   uint32      `json:"cacheSize,omitempty"`
    Min         int64       `json:"min,omitempty"`
    Max         int64       `json:"max,omitempty"`
    TimeQuantum TimeQuantum `json:"timeQuantum,omitempty"`
}
```
I'm working on that in several steps. Waiting for review each time so I don't push up one huge PR.

It would be good for you to review that PR and provide any feedback on the direction it's going.

**Comment by yuce** [comment]
@travisturner Thanks for letting me know about the upcoming changes in that PR.

**Comment by yuce** [comment]
It's already possible to pass `CacheTypeRanked`, `CacheTypeLRU`, or `CacheTypeDefault` as a frame option. Closing.
