### ISSUE TITLE
integration tests should use MustRunCluster and not rely on external Pilosa

### ISSUE THREAD

**Issue by jaffee** [pilosa/go-pilosa#158]
github.com/pilosa/pilosa/test exposes a "MustRunCluster" which is useful for creating and destroying temporary clusters to test against. We no longer need to rely on an externally running Pilosa instance for client integration tests.

Furthermore, we should remove the `// +build integration` tags so that all tests run on every test run. The build tags sometimes break automated code analysis and refactoring tools (such as gorename which ignores them by default), so removing them will simplify things.

**Comment by codysoyland** [comment]
I spent some time on this and got it working on one test, but I realized that using MustRunCluster would lock us into only testing one Pilosa version, and it would be impossible to run integration tests coupling different versions of the client and server.

I decided instead to make it easier to run the test suite with a temporary Pilosa server by automating that in the Makefile. I also added a Travis CI matrix configuration to test different versions of Pilosa. PR is here: https://github.com/pilosa/go-pilosa/pull/167

**Comment by codysoyland** [comment]
I determined that a better path for this would be to switch to CircleCI (as we have for Pilosa server), which allows running the integration tests in separate containers and makes it easier to parameterize. This is now merged (PR #179).
