### ISSUE TITLE
Issue with error handling in import_manager.go

### ISSUE THREAD

**Issue by dmibor** [pilosa/go-pilosa#188]
Hi Everyone!

Think found an issue with error handling in import_manager.go line 147.
```
			for shard, records := range batchForShard {
				if len(records) == 0 {
					continue
				}
				err = importRecords(shard, records)
		=====>		if err != nil {
					break
				}
				batchForShard[shard] = nil
			}
```

Right now when importRecords func returns an error - it silently aborts importing other shards by breaking the loop and continues to read from recordChan, does not free memory and then continue appending records to batchForShard which leads to unbounded growth of batchForShard that eventually causes OOM if importRecords always return error.  

Think would be good to improve this behavior, 
error returned from ImportRecord should not be silent - takes a while to understand what is going on when errors returned by pilosa cluster silently dropped,
also should be a way to avoid OOM,
and maybe not aborting other shards imports in case the error returned by cluster is shard specific (for example in my case the situation was caused by Pilosa node returning 412 code since it didn't own the shard trying to import to it)

**Comment by yuce** [comment]
Hi @dmibor, thanks for your issue report. We are going to resolve this one soon.

**Comment by yuce** [comment]
@dmibor We have pushed a fix to this issue. Does it work for you?
