### ISSUE TITLE
make import-roaring the default

### ISSUE THREAD

**Issue by jaffee** [pilosa/go-pilosa#226]
We talked about this a bit in https://github.com/pilosa/pdk/issues/117 but the more I think about, the more I think it makes sense for import-roaring to be the default. 

It's enormously faster, and avoids a lot of memory pressure on Pilosa for time fields. Since turning it on is really an implementation detail from the perspective of a user of the client library, I don't see much downside to doing it.

On the other hand, if we leave it off by default, users of go-pilosa will see bad performance by default.

Since we're probably going to move everything in the direction of roaring imports and deprecate regular imports, it would make sense to me to exercise them by default.

**Comment by yuce** [comment]
One thing to consider is, when roaring import is enabled, key translation is also enabled. If we make roaring import the default we probably should introduce an option to to enable/disable key translation.
