### ISSUE TITLE
add tracing support

### ISSUE THREAD

**Issue by jaffee** [pilosa/go-pilosa#228]
I think it should be possible to get traces which show timings from when an (e.g.) import request is made on the client to when it's processed on the server, and back. This would allow us to see how much latency is eaten up in network and net/http processing before getting to Pilosa's handler.

Pilosa has numerous examples of how to implement tracing in Go including going between hosts.

**Comment by yuce** [comment]
Implemented with: https://github.com/pilosa/go-pilosa/pull/229
