### ISSUE TITLE
memory usage got large

### ISSUE THREAD

**Issue by seebs** [pilosa/go-pilosa#257]
Memory usage is unreasonably large. This is partially because of a recent change which makes the record importers accept slices of records over their channels, but partially because, for quite a long time before that, the channels in question have been requesting a buffer length of the current batch size. I don't think that makes much sense, but it's particularly a problem in cases where imports are waiting on the server most of the time, because if you set a reasonably large batch size (say, 65536), and you have 16 records per slice dumped into the work queue, you're now up to 1M records waiting in that work queue, per import worker, and suddenly you have 30GB of memory in use and the GC is chewing up a lot of time.

**Comment by travisturner** [comment]
@seebs is this ready to close?

**Comment by seebs** [comment]
Oh, right. Fixed in pull #258, apparently.
