### ISSUE TITLE
Should create only 1 net/http client per node and re-use it

### ISSUE THREAD

**Issue by jaffee** [pilosa/go-pilosa#48]
Currently, go-pilosa is structured such that it creates lots of net/http.Client objects during the course of execution (especially during imports which was partially addressed in #46). The http.Client object is goroutine safe, and meant to be re-used (it may keep TCP connections open internally which would improve latency/efficiency). I think we just need to create one http.Client per host in the cluster, and re-use that in all interactions with a given host.

**Comment by tgruben** [comment]
why not just reply to #46?

**Comment by jaffee** [comment]
sorry, for some reason, I thought that was merged.

**Comment by jaffee** [comment]
turns out we don't even need one http client per host - we just need one

**Comment by yuce** [comment]
Fixed by #60 @jaffee
