### ISSUE TITLE
Client.ImportNode ignores error

### ISSUE THREAD

**Issue by jaffee** [pilosa/go-pilosa#49]
```
 func (c *Client) importNode(request *internal.ImportRequest) error {
	data, _ := proto.Marshal(request)
	// request.Marshal never returns an error
```

`proto.Marshal` attempts to cast `request` to a `Marshaler`, but `*internal.ImportRequest` doesn't implement `Marshal()`,  so `proto.Marshal` goes down another path which it appears may return an error. We should probably just handle the error anywhere `proto.Marshal` is called regardless of whether the object in question is a `Marshaler` in order to be consistent, suppress warnings, and protect against future changes to generated code.

**Comment by yuce** [comment]
Fixed by https://github.com/pilosa/go-pilosa/pull/60 @jaffee
